# visualization.py
# ----------------------------------------------------------------------
# This file was (mostly) generated by chatGPT
# Don't worry about this
# ----------------------------------------------------------------------

import matplotlib.pyplot as plt

from pricing import sample_blocked_path, reflect_path


# --- STYLE: the single place where "what it looks like" is defined -----

STYLE = {
    # colours
    "blocked":      "#2a6fb0",   # blocked path, endpoint x, tree node edge
    "mirror":       "#e08a1e",   # reflected path, endpoint 2B - x
    "barrier":      "#e8453c",   # barrier line and forbidden zone
    "barrier_dark": "#b5302a",   # barrier-related text labels
    "shared":       "0.25",      # shared prefix before the first hit
    "lattice":      "0.8",       # faint lattice edges
    "fold":         "0.6",       # vertical mirror-pair connectors
    "arrow":        "0.4",       # equal-distance arrows
    "annot":        "0.35",      # small annotation text
    "node_face":    "#dce6f0",   # binomial-tree node fill
    # weights & alpha
    "path_lw":      3,           # path line width
    "ref_lw":       2.2,         # barrier line width
    "zone_alpha":   0.07,        # forbidden-zone shading
}


# --- helpers -----------------------------------------------------------

def _cumulative(moves):
    """Turn a list of +-1 moves into the positions visited, starting at 0."""
    pts = [0]
    for m in moves:
        pts.append(pts[-1] + m)
    return pts


def _finish(fig, outfile):
    """Save the figure to disk if outfile is given, else show it."""
    fig.tight_layout()
    if outfile:
        fig.savefig(outfile, dpi=130, bbox_inches="tight")
        print(f"saved {outfile}")
    else:
        plt.show()


# --- figures -----------------------------------------------------------

def draw_binomial_tree(N=3, S0=100, u=1.1, outfile=None):
    """Draw the recombining binomial price lattice (section 4)."""
    fig, ax = plt.subplots(figsize=(7, 4.8))
    for t in range(N + 1):
        for x in range(-t, t + 1, 2):
            if t < N:
                ax.plot([t, t + 1], [x, x + 1], color=STYLE["lattice"],
                        lw=1, zorder=1)
                ax.plot([t, t + 1], [x, x - 1], color=STYLE["lattice"],
                        lw=1, zorder=1)
            ax.plot(t, x, "o", ms=24, color=STYLE["node_face"],
                    mec=STYLE["blocked"], mew=1.4, zorder=2)
            ax.text(t, x, f"{S0 * u ** x:.1f}", ha="center", va="center",
                    fontsize=8, zorder=3)
    ax.set_xlabel("time step  t")
    ax.set_ylabel("net up-displacement  x")
    ax.set_title(f"Recombining binomial price tree   (N={N}, S0={S0}, u={u})")
    ax.set_xticks(range(N + 1))
    ax.spines[["top", "right"]].set_visible(False)
    _finish(fig, outfile)


def draw_reflection(N, x_end, B, seed=0, outfile=None):
    """Draw the reflection bijection: a blocked path and its mirror image."""
    moves = sample_blocked_path(N, x_end, B, seed=seed)
    if moves is None:
        raise RuntimeError("No blocked path found - try another seed/endpoint.")
    reflected, hit = reflect_path(moves, B)

    blocked_pts = _cumulative(moves)
    reflected_pts = _cumulative(reflected)
    times = list(range(N + 1))
    x_refl_end = 2 * B - x_end

    fig, ax = plt.subplots(figsize=(11, 6.3))

    # forbidden zone: at or above the barrier
    ax.axhspan(B, B + N, color=STYLE["barrier"], alpha=STYLE["zone_alpha"],
               zorder=0)

    # faint diamond lattice
    for t in range(N):
        for y in range(-t, t + 1, 2):
            ax.plot([t, t + 1], [y, y + 1], color=STYLE["lattice"],
                    lw=0.5, zorder=1)
            ax.plot([t, t + 1], [y, y - 1], color=STYLE["lattice"],
                    lw=0.5, zorder=1)

    # three reference levels
    ax.axhline(B, color=STYLE["barrier"], ls="--", lw=STYLE["ref_lw"], zorder=2)
    ax.axhline(x_end, color=STYLE["blocked"], ls=":", lw=1.5, zorder=2)
    ax.axhline(x_refl_end, color=STYLE["mirror"], ls=":", lw=1.5, zorder=2)

    # shared prefix before the first hit
    ax.plot(times[:hit + 2], blocked_pts[:hit + 2], color=STYLE["shared"],
            lw=STYLE["path_lw"], zorder=5, solid_capstyle="round")

    # vertical fold lines: each point and its mirror image
    for t in range(hit + 1, N + 1):
        ax.plot([t, t], [blocked_pts[t], reflected_pts[t]],
                color=STYLE["fold"], lw=0.8, ls=(0, (1, 2)), zorder=3)

    # the two tails after the first hit
    ax.plot(times[hit + 1:], blocked_pts[hit + 1:], color=STYLE["blocked"],
            lw=STYLE["path_lw"], zorder=5, solid_capstyle="round",
            label="blocked path  (ends at x)")
    ax.plot(times[hit + 1:], reflected_pts[hit + 1:], color=STYLE["mirror"],
            lw=STYLE["path_lw"], zorder=5, solid_capstyle="round",
            label="mirror image  (ends at 2B - x)")

    # first-hit marker
    ax.plot(hit + 1, B, marker="*", ms=22, color=STYLE["barrier"],
            mec="white", mew=1.2, zorder=6)
    ax.annotate("first hit  d", (hit + 1, B),
                textcoords="offset points", xytext=(-46, 16),
                fontsize=11, color=STYLE["barrier_dark"], fontweight="bold")

    # endpoint dots
    ax.plot(N, x_end, "o", ms=11, color=STYLE["blocked"], mec="white",
            mew=1.5, zorder=6)
    ax.plot(N, x_refl_end, "o", ms=11, color=STYLE["mirror"], mec="white",
            mew=1.5, zorder=6)

    # right-edge level labels
    box = dict(boxstyle="round,pad=0.15", fc="white", ec="none")
    ax.text(N + 0.5, B, f" B = {B}", va="center", fontsize=11,
            color=STYLE["barrier_dark"], fontweight="bold", bbox=box)
    ax.text(N + 0.5, x_end, f" x = {x_end}", va="center", fontsize=11,
            color=STYLE["blocked"], fontweight="bold", bbox=box)
    ax.text(N + 0.5, x_refl_end, f" 2B - x = {x_refl_end}", va="center",
            fontsize=11, color=STYLE["mirror"], fontweight="bold", bbox=box)

    # equal-distance arrows
    d = B - x_end
    ax.annotate("", xy=(N + 2.3, B), xytext=(N + 2.3, x_end),
                arrowprops=dict(arrowstyle="<->", color=STYLE["arrow"], lw=1.3))
    ax.annotate("", xy=(N + 2.3, x_refl_end), xytext=(N + 2.3, B),
                arrowprops=dict(arrowstyle="<->", color=STYLE["arrow"], lw=1.3))
    ax.text(N + 2.7, (B + x_end) / 2, f"d = {d}", va="center",
            fontsize=10, color=STYLE["annot"])
    ax.text(N + 2.7, (B + x_refl_end) / 2, f"d = {d}", va="center",
            fontsize=10, color=STYLE["annot"])

    ax.set_xlim(-0.5, N + 6)
    ax.set_ylim(min(blocked_pts) - 1.5, x_refl_end + 2)
    ax.set_xlabel("time step  t", fontsize=11)
    ax.set_ylabel("net up-displacement  x", fontsize=11)
    ax.set_title("The reflection bijection: one blocked path  <->  one path to 2B - x",
                 fontsize=12.5, pad=12)
    ax.legend(loc="lower left", fontsize=10, framealpha=0.95)
    ax.spines[["top", "right"]].set_visible(False)
    _finish(fig, outfile)
